FROM node:20-alpine
RUN apk add --no-cache wget
WORKDIR /app

ARG NEXT_PUBLIC_EXTERNAL_URL
ARG NEXT_PUBLIC_BASIC_URL
ARG MONGODB_URI
ARG JWT_SECRET
ARG EMAIL_SERVER_HOST
ARG EMAIL_SERVER_PORT
ARG EMAIL_SERVER_USER
ARG EMAIL_SERVER_PASSWORD
ARG REDIS_URL

ENV NEXT_PUBLIC_EXTERNAL_URL=${NEXT_PUBLIC_EXTERNAL_URL}
ENV NEXT_PUBLIC_BASIC_URL=${NEXT_PUBLIC_BASIC_URL}
ENV MONGODB_URI=${MONGODB_URI}
ENV JWT_SECRET=${JWT_SECRET}
ENV EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
ENV EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
ENV EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
ENV EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
ENV REDIS_URL=${REDIS_URL}

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
