FROM node:20-alpine
WORKDIR /app

ARG NEXT_PUBLIC_EXTERNAL_URL
ARG NEXT_PUBLIC_BASIC_URL
ARG MONGODB_URI

ENV NEXT_PUBLIC_EXTERNAL_URL=${NEXT_PUBLIC_EXTERNAL_URL}
ENV NEXT_PUBLIC_BASIC_URL=${NEXT_PUBLIC_BASIC_URL}

COPY package*.json ./
RUN npm install
COPY . .
RUN MONGODB_URI=${MONGODB_URI} npm run build
EXPOSE 3000
CMD ["npm", "start"]
